# Generated by Django 5.0.11 on 2025-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_created_user_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
